### ISSUE TITLE
Remove typing from all game files

### ISSUE THREAD

**Issue by owalk** [m-one-w/M1WEngine#119]
<a href="https://github.com/Sean-Nishi"><img src="https://avatars.githubusercontent.com/u/22729669?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Sean-Nishi](https://github.com/Sean-Nishi)**
_Wednesday Dec 27, 2023 at 22:06 GMT_
_Originally opened as https://github.com/Sean-Nishi/M1Wengine/issues/316_

----

Remove stale "from typing import ..." from all files.
Most common used is List

**Comment by Sean-Nishi** [comment]
Already resolved. Last three instances of "from typing import ..." in the engine are needed to declare Callable and TypeDict
