### ISSUE TITLE
NPC only throws when collisions resolves

### ISSUE THREAD

**Issue by owalk** [m-one-w/M1WEngine#155]
<a href="https://github.com/owalk"><img src="https://avatars.githubusercontent.com/u/10580211?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [owalk](https://github.com/owalk)**
_Wednesday Jan 10, 2024 at 19:47 GMT_
_Originally opened as https://github.com/Sean-Nishi/M1Wengine/issues/359_

----

While currently touching an NPC, the throw will not execute.
Throw only executes when no longer touching NPC.

This logic seems wrong. Change to throw after some condition such as a tile has been traversed, or a certain amount of time has passed, or immediately throw

**Comment by fcpoloia** [comment]
issue seems to be here

elif current_player_action == Actions.throw:
                self.set_state_thrown()

the NPC will change it's state to thrown() only if player state is also thrown()

**Comment by owalk** [comment]
thanks! Feel free to submit a PR if you want :)

Otherwise, I'll try and get to this shortly
