### ISSUE TITLE
Discord setup for public engine

### ISSUE THREAD

**Issue by owalk** [m-one-w/M1WEngine#207]
<a href="https://github.com/owalk"><img src="https://avatars.githubusercontent.com/u/10580211?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [owalk](https://github.com/owalk)**
_Wednesday Feb 07, 2024 at 19:10 GMT_
_Originally opened as https://github.com/Sean-Nishi/M1Wengine/issues/417_

----

Make a discord channel for the game engine

Add it to the game engine readme

**Comment by fcpoloia** [comment]
My guy, you have added like 200 issues in 30 minutes

**Comment by owalk** [comment]
lol I have a script migrating issues over from the old repository on @Sean-Nishi 's account. I wanted to add all 500 of them, but there's not a great way to migrate closed issues :(

**Comment by owalk** [comment]
https://discord.gg/HCy8fheqqw
